/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    LoginLeftView: typeof import('./../components/core/views/login/LoginLeftView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarSubmenu: typeof import('./../components/core/layouts/wellnest-sidebar-menu/widget/SidebarSubmenu.vue')['default']
    WellnestButtonMore: typeof import('./../components/core/forms/wellnest-button-more/index.vue')['default']
    WellnestFormActions: typeof import('./../components/core/forms/wellnest-form-actions/index.vue')['default']
    WellnestFormAuth: typeof import('./../components/core/forms/wellnest-form-auth/index.vue')['default']
    WellnestHeaderBar: typeof import('./../components/core/layouts/wellnest-header-bar/index.vue')['default']
    WellnestPageContent: typeof import('./../components/core/layouts/wellnest-page-content/index.vue')['default']
    WellnestSidebarMenu: typeof import('./../components/core/layouts/wellnest-sidebar-menu/index.vue')['default']
    WellnestTable: typeof import('./../components/core/tables/wellnest-table/index.vue')['default']
    WellnestTableHeader: typeof import('./../components/core/tables/wellnest-table-header/index.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
